Feature/top up
Kukuza/mobile-wallet pull request #38
Opened 2022-04-07 13:17 UTC by Alphonce-Mutebi

+ Integrated agentAcceptDepositTransaction contract calls
+ Integrated agentAcceptWithdrawalTransaction contract calls

2022-04-08 00:07 UTC, steffenkrogmann approved these changes

2022-04-08 07:30 UTC, Allen-Muhani requested changes

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionConfirmationScreen.tsx
> +  const publicAddress = "0x9FDf3F87CbEE162DC4a9BC9673E5Bb6716186757";
Why is this hardocded?

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionConfirmationScreen.tsx
> +    lineHeight: 24,
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionSuccess.tsx
> +    lineHeight: FONTS.headline.lineHeight,
All the first three lines of code should be one line of code.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TopUpViewRequestScreen.tsx
> +    lineHeight: 24,
use entralized styling text.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TopUpViewRequestScreen.tsx
> +    color: "#333333",
use entralized styling text.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TopUpViewRequestScreen.tsx
> +    color: "#133FDB",
use centralized styling text and color.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionConfirmationScreen.tsx
> +    color: "#333333",
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionConfirmationScreen.tsx
> +    color: "#133FDB",
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionSuccess.tsx
> +    fontFamily: FONTS.displayBold.fontFamily,
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionSuccess.tsx
> +    fontSize: FONTS.headline.fontSize,
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionSuccess.tsx
> +    fontFamily: FONTS.body3.fontFamily,
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionSuccess.tsx
> +    fontFamily: FONTS.sh2.fontFamily,
use centralized text styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TransactionConfirmationScreen.tsx
> +              name="checkmark-circle"
use centralized color styling.

2022-04-08 07:30 UTC, Allen-Muhani commented on src/screens/TransactionRequests/TopUpViewRequestScreen.tsx
> -            </View>
Why not use the large modal file as utils?

2022-04-11 13:42 UTC, Allen-Muhani approved these changes

2022-04-11 13:42 UTC, merged